# Generated by Django 4.1.4 on 2022-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, help_text='Marokash', max_length=255, null=True, verbose_name='Vatani'),
        ),
    ]
